apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gopal-ingress
  annotations:
    # Tell Kubernetes we are using the Nginx controller we just installed
    kubernetes.io/ingress.class: nginx
    # Optimization: connection keep-alive
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      # Rule 1: Traffic for /api/a goes to Backend A
      - path: /api/a
        pathType: Prefix
        backend:
          service:
            name: backend-a
            port:
              number: 80
      # Rule 2: Traffic for /api/b goes to Backend B
      - path: /api/b
        pathType: Prefix
        backend:
          service:
            name: backend-b
            port:
              number: 80